### ISSUE TITLE
About data preprocess

### ISSUE THREAD

**Issue by ProfXGiter** [EhsanMashhadi/MSR2021-ProgramRepair#1]
Hi,  this project is a excellent work.
I wonder how to preprocess the data.

**Comment by EhsanMashhadi** [comment]
Hi,

Thanks for reaching out. What do you mean exactly by preprocessing the data? We collected the patches from the ManySStuBs4J [dataset](https://dl.acm.org/doi/10.1145/3379597.3387491) which is provided in JSON format. 

Do you need a specific script or any clarification?

**Comment by August1s** [comment]
Hi,
I am facing the same issue about data preprocess and running. 
`./scripts/simple-lstm/preprocess.sh` execute the command `python $OpenNMT_py/preprocess.py`. However, lasted version of OpenNMT-py does not contain `preprocess.py`.
How can I get this file? Which version of OpenNMT-py is used for this project?

**Comment by EhsanMashhadi** [comment]
Hi @August1s ,

Please check the legacy version:
https://github.com/OpenNMT/OpenNMT-py/tree/legacy

You can also change the script a bit to make it compatible with the latest version of OpenNMT-PY and your PR is welcome!
